version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - AWS_DEFAULT_REGION=us-east-1
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=500986409600.dkr.ecr.us-east-1.amazonaws.com/dotnet-my-api-new
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - git clone https://github.com/ratulbasak/aws_fargate_api.git
      - pwd
      - cd aws_fargate_api/
      - echo Building the Docker image... 
      - docker build -t dotnet-my-api-new .
      #- docker tag dotnet-my-api-new:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker tag dotnet-my-api-new:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"dotnet-api","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
